apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lot.fullname" . }}-celery-worker
  labels:
    {{- include "lot.labels" . | nindent 4 }}
    app.kubernetes.io/component: celery-worker
spec:
  replicas: {{ .Values.celery.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: celery-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: celery-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: celery-worker
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["celery", "-A", "app.celery_app", "worker", "-l", "info"]
          envFrom:
            - secretRef:
                name: {{ include "lot.fullname" . }}-secrets
            - configMapRef:
                name: {{ include "lot.fullname" . }}-config
