apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lot.fullname" . }}-secrets
  labels:
    {{- include "lot.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CELERY_BROKER_URL: {{ .Values.secrets.celeryBrokerUrl | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.secrets.celeryResultBackend | quote }}
  DISCORD_WEBHOOK_URL: {{ .Values.secrets.discordWebhookUrl | quote }}
  LIMITLESS_USERNAME: {{ .Values.secrets.limitlessUsername | quote }}
  LIMITLESS_PASSWORD: {{ .Values.secrets.limitlessPassword | quote }}
