FROM python:3.12-slim AS build

WORKDIR /app

RUN pip install --no-cache-dir "mkdocs>=1.6" "mkdocs-material>=9.5"

COPY mkdocs.yml ./
COPY docs/ ./docs/
RUN mkdocs build --strict

FROM nginx:alpine

COPY --from=build /app/site /usr/share/nginx/html
COPY nginx.docs.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
