"""add_organizers_table

Revision ID: 59209420e443
Revises: ff32d370af50
Create Date: 2026-06-18 10:16:26.228938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59209420e443'
down_revision: Union[str, None] = 'ff32d370af50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizers',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('onboarded_at', sa.Date(), nullable=True),
    sa.Column('first_tournament_date', sa.Date(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('organizer_id')
    )
    op.create_index(op.f('ix_organizers_onboarded_at'), 'organizers', ['onboarded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizers_onboarded_at'), table_name='organizers')
    op.drop_table('organizers')
    # ### end Alembic commands ###
