"""initial tables

Revision ID: 904571dc5664
Revises: 
Create Date: 2026-06-12 02:52:19.264671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904571dc5664'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'UNKNOWN', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_checks_checked_at'), 'application_status_checks', ['checked_at'], unique=False)
    op.create_table('organizer_activity',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('first_tournament_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_tournament_id', sa.String(), nullable=False),
    sa.Column('last_seen_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organizer_id', 'game')
    )
    op.create_index(op.f('ix_organizer_activity_first_tournament_date'), 'organizer_activity', ['first_tournament_date'], unique=False)
    op.create_table('resubmission_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('discord_notified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resubmission_events_submitted_at'), 'resubmission_events', ['submitted_at'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('players', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_date'), 'tournaments', ['date'], unique=False)
    op.create_index(op.f('ix_tournaments_game'), 'tournaments', ['game'], unique=False)
    op.create_index(op.f('ix_tournaments_organizer_id'), 'tournaments', ['organizer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_organizer_id'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_game'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_date'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_resubmission_events_submitted_at'), table_name='resubmission_events')
    op.drop_table('resubmission_events')
    op.drop_index(op.f('ix_organizer_activity_first_tournament_date'), table_name='organizer_activity')
    op.drop_table('organizer_activity')
    op.drop_index(op.f('ix_application_status_checks_checked_at'), table_name='application_status_checks')
    op.drop_table('application_status_checks')
    # ### end Alembic commands ###
