"""add_index_on_organizers_detected_at

Revision ID: 9be0f1da5379
Revises: c4a1e8b93d71
Create Date: 2026-06-25 12:53:59.228749

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9be0f1da5379'
down_revision: Union[str, None] = 'c4a1e8b93d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organizers_detected_at'), 'organizers', ['detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizers_detected_at'), table_name='organizers')
    # ### end Alembic commands ###
