"""add index on organizer_activity.game

Revision ID: d7c22892b275
Revises: b7e3a1f2c456
Create Date: 2026-06-22 11:09:27.849894

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd7c22892b275'
down_revision: Union[str, None] = 'b7e3a1f2c456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organizer_activity_game'), 'organizer_activity', ['game'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizer_activity_game'), table_name='organizer_activity')
    # ### end Alembic commands ###
