"""add review_note to application_status_checks

Revision ID: ff32d370af50
Revises: a32d43dfddd8
Create Date: 2026-06-18 03:13:12.896055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff32d370af50'
down_revision: Union[str, None] = 'a32d43dfddd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_status_checks', sa.Column('review_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_status_checks', 'review_note')
    # ### end Alembic commands ###
